name: "Async CI"

on:
  push:
    branches:
      - master
      - hotfix
    paths:
      - ".github/workflows/**"
      - "Package.swift"
      - "Source/**"
      - "Tests/**"
  pull_request:
    paths:
      - ".github/workflows/**"
      - "Package.swift"
      - "Source/**"
      - "Tests/**"

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  SPM:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runsOn }}
    env:
      DEVELOPER_DIR: "/Applications/${{ matrix.xcode }}.app/Contents/Developer"
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode: "Xcode_15.0"
            runsOn: macOS-14
            name: "macOS 14, SPM 5.9.0 Test"
          - xcode: "Xcode_14.3.1"
            runsOn: macOS-13
            name: "macOS 13, SPM 5.8.0 Test"
          - xcode: "Xcode_14.2"
            runsOn: macOS-12
            name: "macOS 12, SPM 5.7.2 Test"
          - xcode: "Xcode_14.1"
            runsOn: macOS-12
            name: "macOS 12, SPM 5.7.1 Test"
          - xcode: "Xcode_14.0.1"
            runsOn: macOS-12
            name: "macOS 12, SPM 5.7.0 Test"
    steps:
      - uses: actions/checkout@v4
      - name: Test SPM
        run: swift test -c debug
